name: Flake8

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - master

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8.7
          architecture: x64
      - name: Install flake8
        run: pip install flake8
      - name: Run flake8
        run: flake8